export enum Results {
  "Ace" = 0,
  "Kill" = 1,
  "Zero Serve" = 2,
  "Pass" = 3,
  "Free Ball" = 4,
  "Zero Atk" = 5,
  "Set" = 6,
  "Block" = 7,
  "Zero Block" = 8,
  "Block Touch" = 9,
  "No Block" = 10,
  "Dead Ball" = 11,
  "Rec. Err" = 12,
  "Serve Err" = 13,
  "BH Err" = 14,
  "Atk Err" = 15,
  "Block Err" = 16,
  "Undecided" = 17
}
